export const sample  = [
    {
        id: 2292,
        common_name: 'tree tomato',
        scientific_name: [ 'Cyphomandra betacea' ],
        other_name: [],
        family: 'Solanaceae',
        hybrid: null,
        authority: null,
        subspecies: null,
        cultivar: null,
        variety: null,
        species_epithet: 'betacea',
        genus: 'Cyphomandra',
        default_image: {
            license: 5,
            license_name: 'Attribution-ShareAlike License',
            license_url: 'https://creativecommons.org/licenses/by-sa/2.0/',
            original_url: 'https://perenual.com/storage/species_image/2292_cyphomandra_betacea/og/49288036626_f4bfa5c8c5_b.jpg',
            regular_url: 'https://perenual.com/storage/species_image/2292_cyphomandra_betacea/regular/49288036626_f4bfa5c8c5_b.jpg',
            medium_url: 'https://perenual.com/storage/species_image/2292_cyphomandra_betacea/medium/49288036626_f4bfa5c8c5_b.jpg',
            small_url: 'https://perenual.com/storage/species_image/2292_cyphomandra_betacea/small/49288036626_f4bfa5c8c5_b.jpg',
            thumbnail: 'https://perenual.com/storage/species_image/2292_cyphomandra_betacea/thumbnail/49288036626_f4bfa5c8c5_b.jpg'
        }
    },
    {
        id: 2692,
        common_name: 'coneflower',
        scientific_name: [ "Echinacea 'Tomato Soup'" ],
        other_name: [],
        family: 'Asteraceae',
        hybrid: null,
        authority: null,
        subspecies: null,
        cultivar: 'Tomato Soup',
        variety: null,
        species_epithet: "'Tomato",
        genus: 'Echinacea',
        default_image: {
            license: 451,
            license_name: 'CC0 1.0 Universal (CC0 1.0) Public Domain Dedication',
            license_url: 'https://creativecommons.org/publicdomain/zero/1.0/',
            original_url: 'https://perenual.com/storage/species_image/2692_echinacea_tomato_soup/og/red-orange-echinacea-echinacea-cone-flower-medicinal.jpg',
            regular_url: 'https://perenual.com/storage/species_image/2692_echinacea_tomato_soup/regular/red-orange-echinacea-echinacea-cone-flower-medicinal.jpg',
            medium_url: 'https://perenual.com/storage/species_image/2692_echinacea_tomato_soup/medium/red-orange-echinacea-echinacea-cone-flower-medicinal.jpg',
            small_url: 'https://perenual.com/storage/species_image/2692_echinacea_tomato_soup/small/red-orange-echinacea-echinacea-cone-flower-medicinal.jpg',
            thumbnail: 'https://perenual.com/storage/species_image/2692_echinacea_tomato_soup/thumbnail/red-orange-echinacea-echinacea-cone-flower-medicinal.jpg'
        }
    },
    {
        id: 3849,
        common_name: 'hosta',
        scientific_name: [ "Hosta 'Cherry Tomato'" ],
        other_name: [],
        family: 'Asparagaceae',
        hybrid: null,
        authority: null,
        subspecies: null,
        cultivar: 'Cherry Tomato',
        variety: null,
        species_epithet: "'Cherry",
        genus: 'Hosta',
        default_image: {
            license: 451,
            license_name: 'CC0 1.0 Universal (CC0 1.0) Public Domain Dedication',
            license_url: 'https://creativecommons.org/publicdomain/zero/1.0/',
            original_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            regular_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            medium_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            small_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            thumbnail: 'https://perenual.com/storage/image/upgrade_access.jpg'
        }
    },
    {
        id: 4943,
        common_name: 'cardinal flower',
        scientific_name: [ "Lobelia cardinalis 'Fried Green Tomatoes'" ],
        other_name: [],
        family: 'Campanulaceae',
        hybrid: null,
        authority: null,
        subspecies: null,
        cultivar: 'Fried Green Tomatoes',
        variety: null,
        species_epithet: 'cardinalis',
        genus: 'Lobelia',
        default_image: {
            license: 451,
            license_name: 'CC0 1.0 Universal (CC0 1.0) Public Domain Dedication',
            license_url: 'https://creativecommons.org/publicdomain/zero/1.0/',
            original_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            regular_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            medium_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            small_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            thumbnail: 'https://perenual.com/storage/image/upgrade_access.jpg'
        }
    },
    {
        id: 5021,
        common_name: 'tomato',
        scientific_name: [ 'Lycopersicon esculentum' ],
        other_name: [],
        family: 'Solanaceae',
        hybrid: null,
        authority: null,
        subspecies: null,
        cultivar: null,
        variety: null,
        species_epithet: 'esculentum',
        genus: 'Lycopersicon',
        default_image: {
            license: 451,
            license_name: 'CC0 1.0 Universal (CC0 1.0) Public Domain Dedication',
            license_url: 'https://creativecommons.org/publicdomain/zero/1.0/',
            original_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            regular_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            medium_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            small_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            thumbnail: 'https://perenual.com/storage/image/upgrade_access.jpg'
        }
    },
    {
        id: 5022,
        common_name: 'tomato',
        scientific_name: [ "Lycopersicon esculentum 'Big Beef'" ],
        other_name: [],
        family: 'Solanaceae',
        hybrid: null,
        authority: null,
        subspecies: null,
        cultivar: 'Big Beef',
        variety: null,
        species_epithet: 'esculentum',
        genus: 'Lycopersicon',
        default_image: {
            license: 451,
            license_name: 'CC0 1.0 Universal (CC0 1.0) Public Domain Dedication',
            license_url: 'https://creativecommons.org/publicdomain/zero/1.0/',
            original_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            regular_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            medium_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            small_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            thumbnail: 'https://perenual.com/storage/image/upgrade_access.jpg'
        }
    },
    {
        id: 5023,
        common_name: 'tomato',
        scientific_name: [ "Lycopersicon esculentum 'Chef's Choice Orange'" ],
        other_name: [],
        family: 'Solanaceae',
        hybrid: null,
        authority: null,
        subspecies: null,
        cultivar: 'Chef',
        variety: null,
        species_epithet: 'esculentum',
        genus: 'Lycopersicon',
        default_image: {
            license: 451,
            license_name: 'CC0 1.0 Universal (CC0 1.0) Public Domain Dedication',
            license_url: 'https://creativecommons.org/publicdomain/zero/1.0/',
            original_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            regular_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            medium_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            small_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            thumbnail: 'https://perenual.com/storage/image/upgrade_access.jpg'
        }
    },
    {
        id: 5024,
        common_name: 'tomato',
        scientific_name: [ "Lycopersicon esculentum 'Pink Girl'" ],
        other_name: [],
        family: 'Solanaceae',
        hybrid: null,
        authority: null,
        subspecies: null,
        cultivar: 'Pink Girl',
        variety: null,
        species_epithet: 'esculentum',
        genus: 'Lycopersicon',
        default_image: {
            license: 451,
            license_name: 'CC0 1.0 Universal (CC0 1.0) Public Domain Dedication',
            license_url: 'https://creativecommons.org/publicdomain/zero/1.0/',
            original_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            regular_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            medium_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            small_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            thumbnail: 'https://perenual.com/storage/image/upgrade_access.jpg'
        }
    },
    {
        id: 5025,
        common_name: 'tomato',
        scientific_name: [ "Lycopersicon esculentum 'Rapunzel'" ],
        other_name: [],
        family: 'Solanaceae',
        hybrid: null,
        authority: null,
        subspecies: null,
        cultivar: 'Rapunzel',
        variety: null,
        species_epithet: 'esculentum',
        genus: 'Lycopersicon',
        default_image: {
            license: 451,
            license_name: 'CC0 1.0 Universal (CC0 1.0) Public Domain Dedication',
            license_url: 'https://creativecommons.org/publicdomain/zero/1.0/',
            original_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            regular_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            medium_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            small_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            thumbnail: 'https://perenual.com/storage/image/upgrade_access.jpg'
        }
    },
    {
        id: 5026,
        common_name: 'tomato',
        scientific_name: [ "Lycopersicon esculentum 'Sungold'" ],
        other_name: [],
        family: 'Solanaceae',
        hybrid: null,
        authority: null,
        subspecies: null,
        cultivar: 'Sungold',
        variety: null,
        species_epithet: 'esculentum',
        genus: 'Lycopersicon',
        default_image: {
            license: 451,
            license_name: 'CC0 1.0 Universal (CC0 1.0) Public Domain Dedication',
            license_url: 'https://creativecommons.org/publicdomain/zero/1.0/',
            original_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            regular_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            medium_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            small_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            thumbnail: 'https://perenual.com/storage/image/upgrade_access.jpg'
        }
    },
    {
        id: 8759,
        common_name: 'tomato',
        scientific_name: [ 'Solanum lycopersicum' ],
        other_name: [],
        family: 'Solanaceae',
        hybrid: null,
        authority: null,
        subspecies: null,
        cultivar: null,
        variety: null,
        species_epithet: 'lycopersicum',
        genus: 'Solanum',
        default_image: {
            license: 451,
            license_name: 'CC0 1.0 Universal (CC0 1.0) Public Domain Dedication',
            license_url: 'https://creativecommons.org/publicdomain/zero/1.0/',
            original_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            regular_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            medium_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            small_url: 'https://perenual.com/storage/image/upgrade_access.jpg',
            thumbnail: 'https://perenual.com/storage/image/upgrade_access.jpg'
        }
    }
]
